---
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:pr-1282
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - TZ=America/New_York
    ports:
      - '8191:8191'
    restart: unless-stopped
